language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
before_install:
  - if [ "$TRAVIS_PERL_VERSION" = "5.6.2" ]; then rm -f dist.ini; fi # Force Building with Makefile.PL on Perl 5.6.2 as dzil would not work
  - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
  slack:
    rooms:
      - perl-test2:kI7LQjG4iRjIqA2JTl770A5F#general
    on_success: change
